### PR TITLE
Implementing more configurability for the !poll command

### LINKED ISSUE #1: More poll options
It should be possible to create a poll with more than two options to answer.
You could write:
```
!poll <numberOfOptions>
```

I think this would be a nice feature

EDIT: And it would be cool if there was a feature to abstain. The WadzekBot could then add an "X"-Emoji or something like that. This could be turned on or off by using a parameter, like:

```
!poll <numberOfOptions> <skipVotePossible>
```

For that parameter you could then write "skip" or "noSkip" or simply 1 or 0.

### PR DESCRIPTION
**Pull request by kiriDevs**
### New Functionality?
- [X] Adding option to the !poll command to allow a variable number of vote possibilities (2-5) (@Wadzek1)
- [x] Adding option to the !poll command to allow another voting option: "abstain vote" (@kiriDevs)

### Contributors?
- @Wadzek1 wrote all the code
- @kiriDevs re-committed to fix crucial mistakes in the history

### Closes issues?
- Closes #1 (opened by @detiDevs)

### More info?
- @Wadzek1 Please don't mess the commits up that badly again, sitting in a terminal for an hour to fix it was not fun.
- The one hour is not even exaggerated. Help.

### CODE REVIEW

**Comment by kiriDevs** [comment]
Pull request is now up.

@Wadzek1 added as reviewer for draft-pr to check if his code was properly re-implemented.

**Comment by Wadzek1** [comment]
Mache nach der Schule die "abstain vote" - Funktion rein!

**Comment by kiriDevs** [comment]
@Wadzek1 Will you still add the "abstain vote"? I'll take it over if you're OK with that.

**Review by Wadzek1 — APPROVED** [review]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Pull request merged**
